"""
charts_sv.py — Plan de Cuentas El Salvador
============================================
NIIF para las PYMES (CVPCPA El Salvador).
Alineado con DGII para CCF y Facturas de Consumidor Final.
Moneda: USD ($) | IVA: 13% | ISR: 30%
"""

NIIF_SV_ACCOUNTS = [
    # GRUPO 1 — ACTIVO
    {"code":"1101","name":"Caja General","type":"asset","normal":"debit"},
    {"code":"1102","name":"Caja Chica","type":"asset","normal":"debit"},
    {"code":"1103","name":"Bancos Cuenta Corriente","type":"asset","normal":"debit"},
    {"code":"1104","name":"Bancos Cuenta de Ahorro","type":"asset","normal":"debit"},
    {"code":"1105","name":"Depositos a Plazo","type":"asset","normal":"debit"},
    {"code":"1106","name":"Inversiones Temporales","type":"asset","normal":"debit"},
    {"code":"1201","name":"Clientes","type":"asset","normal":"debit"},
    {"code":"1202","name":"Cuentas por Cobrar Comerciales","type":"asset","normal":"debit"},
    {"code":"1203","name":"Documentos por Cobrar","type":"asset","normal":"debit"},
    {"code":"1204","name":"Deudores Varios","type":"asset","normal":"debit"},
    {"code":"1205","name":"Cuentas por Cobrar a Empleados","type":"asset","normal":"debit"},
    {"code":"1206","name":"Anticipo a Proveedores","type":"asset","normal":"debit"},
    {"code":"1207","name":"Prestamos a Accionistas","type":"asset","normal":"debit"},
    {"code":"1208","name":"Estimacion para Cuentas Incobrables","type":"asset","normal":"credit"},
    {"code":"1301","name":"IVA Credito Fiscal","type":"asset","normal":"debit"},
    {"code":"1302","name":"IVA Retenido por Terceros","type":"asset","normal":"debit"},
    {"code":"1303","name":"IVA Percibido Anticipado","type":"asset","normal":"debit"},
    {"code":"1304","name":"Pago a Cuenta ISR","type":"asset","normal":"debit"},
    {"code":"1305","name":"ISR Retenido a Favor","type":"asset","normal":"debit"},
    {"code":"1306","name":"Remanente de Credito Fiscal","type":"asset","normal":"debit"},
    {"code":"1401","name":"Inventario de Mercaderias","type":"asset","normal":"debit"},
    {"code":"1402","name":"Inventario de Materias Primas","type":"asset","normal":"debit"},
    {"code":"1403","name":"Inventario de Productos en Proceso","type":"asset","normal":"debit"},
    {"code":"1404","name":"Inventario de Productos Terminados","type":"asset","normal":"debit"},
    {"code":"1405","name":"Inventario de Materiales y Suministros","type":"asset","normal":"debit"},
    {"code":"1406","name":"Mercaderia en Transito","type":"asset","normal":"debit"},
    {"code":"1407","name":"Estimacion por Obsolescencia de Inventarios","type":"asset","normal":"credit"},
    {"code":"1501","name":"Seguros Pagados por Anticipado","type":"asset","normal":"debit"},
    {"code":"1502","name":"Alquileres Pagados por Anticipado","type":"asset","normal":"debit"},
    {"code":"1503","name":"Papeleria y Utiles","type":"asset","normal":"debit"},
    {"code":"1504","name":"Otros Gastos Pagados por Anticipado","type":"asset","normal":"debit"},
    {"code":"1601","name":"Terrenos","type":"asset","normal":"debit"},
    {"code":"1602","name":"Edificios","type":"asset","normal":"debit"},
    {"code":"1603","name":"Depreciacion Acumulada — Edificios","type":"asset","normal":"credit"},
    {"code":"1604","name":"Maquinaria y Equipo","type":"asset","normal":"debit"},
    {"code":"1605","name":"Depreciacion Acumulada — Maquinaria y Equipo","type":"asset","normal":"credit"},
    {"code":"1606","name":"Mobiliario y Equipo de Oficina","type":"asset","normal":"debit"},
    {"code":"1607","name":"Depreciacion Acumulada — Mobiliario y Equipo","type":"asset","normal":"credit"},
    {"code":"1608","name":"Equipo de Transporte","type":"asset","normal":"debit"},
    {"code":"1609","name":"Depreciacion Acumulada — Equipo de Transporte","type":"asset","normal":"credit"},
    {"code":"1610","name":"Equipo de Computo","type":"asset","normal":"debit"},
    {"code":"1611","name":"Depreciacion Acumulada — Equipo de Computo","type":"asset","normal":"credit"},
    {"code":"1612","name":"Instalaciones y Mejoras","type":"asset","normal":"debit"},
    {"code":"1613","name":"Depreciacion Acumulada — Instalaciones","type":"asset","normal":"credit"},
    {"code":"1701","name":"Marcas y Patentes","type":"asset","normal":"debit"},
    {"code":"1702","name":"Amortizacion Acumulada — Marcas y Patentes","type":"asset","normal":"credit"},
    {"code":"1703","name":"Programas Informaticos (Software)","type":"asset","normal":"debit"},
    {"code":"1704","name":"Amortizacion Acumulada — Software","type":"asset","normal":"credit"},
    {"code":"1705","name":"Derechos de Llave (Goodwill)","type":"asset","normal":"debit"},
    {"code":"1801","name":"Depositos en Garantia","type":"asset","normal":"debit"},
    {"code":"1802","name":"Inversiones Permanentes en Acciones","type":"asset","normal":"debit"},
    {"code":"1803","name":"ISR Diferido Activo","type":"asset","normal":"debit"},
    # GRUPO 2 — PASIVO
    {"code":"2101","name":"Proveedores","type":"liability","normal":"credit"},
    {"code":"2102","name":"Cuentas por Pagar Comerciales","type":"liability","normal":"credit"},
    {"code":"2103","name":"Documentos por Pagar","type":"liability","normal":"credit"},
    {"code":"2104","name":"Acreedores Varios","type":"liability","normal":"credit"},
    {"code":"2105","name":"Anticipo de Clientes","type":"liability","normal":"credit"},
    {"code":"2106","name":"Cuentas por Pagar a Accionistas","type":"liability","normal":"credit"},
    {"code":"2201","name":"IVA Debito Fiscal","type":"liability","normal":"credit"},
    {"code":"2202","name":"IVA por Pagar","type":"liability","normal":"credit"},
    {"code":"2203","name":"IVA Retenido a Terceros","type":"liability","normal":"credit"},
    {"code":"2204","name":"IVA Percibido a Terceros","type":"liability","normal":"credit"},
    {"code":"2205","name":"ISR por Pagar","type":"liability","normal":"credit"},
    {"code":"2206","name":"Pago a Cuenta por Enterar","type":"liability","normal":"credit"},
    {"code":"2207","name":"Retenciones de ISR por Pagar","type":"liability","normal":"credit"},
    {"code":"2208","name":"Impuestos Municipales por Pagar","type":"liability","normal":"credit"},
    {"code":"2301","name":"Sueldos y Salarios por Pagar","type":"liability","normal":"credit"},
    {"code":"2302","name":"Aguinaldos por Pagar","type":"liability","normal":"credit"},
    {"code":"2303","name":"Vacaciones por Pagar","type":"liability","normal":"credit"},
    {"code":"2304","name":"ISSS Cuota Patronal por Pagar","type":"liability","normal":"credit"},
    {"code":"2305","name":"ISSS Cuota Laboral Retenida","type":"liability","normal":"credit"},
    {"code":"2306","name":"AFP Cuota Patronal por Pagar","type":"liability","normal":"credit"},
    {"code":"2307","name":"AFP Cuota Laboral Retenida","type":"liability","normal":"credit"},
    {"code":"2308","name":"INSAFORP por Pagar","type":"liability","normal":"credit"},
    {"code":"2401","name":"Prestamos Bancarios a Corto Plazo","type":"liability","normal":"credit"},
    {"code":"2402","name":"Sobregiros Bancarios","type":"liability","normal":"credit"},
    {"code":"2403","name":"Porcion Circulante de Deuda a Largo Plazo","type":"liability","normal":"credit"},
    {"code":"2404","name":"Intereses por Pagar","type":"liability","normal":"credit"},
    {"code":"2501","name":"Prestamos Bancarios a Largo Plazo","type":"liability","normal":"credit"},
    {"code":"2502","name":"Documentos por Pagar a Largo Plazo","type":"liability","normal":"credit"},
    {"code":"2503","name":"Arrendamiento Financiero por Pagar","type":"liability","normal":"credit"},
    {"code":"2504","name":"Provision para Indemnizaciones","type":"liability","normal":"credit"},
    {"code":"2505","name":"ISR Diferido Pasivo","type":"liability","normal":"credit"},
    # GRUPO 3 — PATRIMONIO
    {"code":"3101","name":"Capital Social","type":"equity","normal":"credit"},
    {"code":"3102","name":"Capital Social No Pagado","type":"equity","normal":"debit"},
    {"code":"3103","name":"Aportes para Futuros Aumentos de Capital","type":"equity","normal":"credit"},
    {"code":"3201","name":"Reserva Legal","type":"equity","normal":"credit"},
    {"code":"3202","name":"Reservas Estatutarias","type":"equity","normal":"credit"},
    {"code":"3203","name":"Reservas Voluntarias","type":"equity","normal":"credit"},
    {"code":"3301","name":"Utilidades de Ejercicios Anteriores","type":"equity","normal":"credit"},
    {"code":"3302","name":"Perdidas de Ejercicios Anteriores","type":"equity","normal":"debit"},
    {"code":"3303","name":"Utilidad del Presente Ejercicio","type":"equity","normal":"credit"},
    {"code":"3304","name":"Perdida del Presente Ejercicio","type":"equity","normal":"debit"},
    {"code":"3401","name":"Superavit por Revaluacion","type":"equity","normal":"credit"},
    # GRUPO 4 — INGRESOS
    {"code":"4101","name":"Ventas de Mercaderias","type":"income","normal":"credit"},
    {"code":"4102","name":"Ventas de Productos Terminados","type":"income","normal":"credit"},
    {"code":"4103","name":"Ingresos por Servicios","type":"income","normal":"credit"},
    {"code":"4104","name":"Ingresos por Comisiones","type":"income","normal":"credit"},
    {"code":"4105","name":"Ingresos por Arrendamiento","type":"income","normal":"credit"},
    {"code":"4106","name":"Ingresos por Exportaciones","type":"income","normal":"credit"},
    {"code":"4201","name":"Devoluciones sobre Ventas","type":"income","normal":"debit"},
    {"code":"4202","name":"Descuentos sobre Ventas","type":"income","normal":"debit"},
    {"code":"4203","name":"Rebajas sobre Ventas","type":"income","normal":"debit"},
    # GRUPO 5 — COSTOS
    {"code":"5101","name":"Costo de Venta de Mercaderias","type":"expense","normal":"debit"},
    {"code":"5102","name":"Costo de Venta de Productos Terminados","type":"expense","normal":"debit"},
    {"code":"5103","name":"Costo de Servicios Prestados","type":"expense","normal":"debit"},
    {"code":"5104","name":"Compras de Mercaderias","type":"expense","normal":"debit"},
    {"code":"5105","name":"Devoluciones sobre Compras","type":"expense","normal":"credit"},
    {"code":"5106","name":"Descuentos sobre Compras","type":"expense","normal":"credit"},
    {"code":"5107","name":"Fletes sobre Compras","type":"expense","normal":"debit"},
    {"code":"5108","name":"Mano de Obra Directa","type":"expense","normal":"debit"},
    {"code":"5109","name":"Costos Indirectos de Fabricacion","type":"expense","normal":"debit"},
    # GRUPO 6 — GASTOS DE OPERACION
    {"code":"6101","name":"Sueldos — Personal de Ventas","type":"expense","normal":"debit"},
    {"code":"6102","name":"Comisiones sobre Ventas","type":"expense","normal":"debit"},
    {"code":"6103","name":"Publicidad y Promocion","type":"expense","normal":"debit"},
    {"code":"6104","name":"Gastos de Distribucion y Envio","type":"expense","normal":"debit"},
    {"code":"6105","name":"Gastos de Almacenaje","type":"expense","normal":"debit"},
    {"code":"6106","name":"Depreciacion — Equipo de Ventas","type":"expense","normal":"debit"},
    {"code":"6107","name":"Gastos de Viaje — Ventas","type":"expense","normal":"debit"},
    {"code":"6108","name":"ISSS Patronal — Ventas","type":"expense","normal":"debit"},
    {"code":"6109","name":"AFP Patronal — Ventas","type":"expense","normal":"debit"},
    {"code":"6201","name":"Sueldos y Salarios — Administracion","type":"expense","normal":"debit"},
    {"code":"6202","name":"Aguinaldos","type":"expense","normal":"debit"},
    {"code":"6203","name":"Vacaciones","type":"expense","normal":"debit"},
    {"code":"6204","name":"ISSS Cuota Patronal","type":"expense","normal":"debit"},
    {"code":"6205","name":"AFP Cuota Patronal","type":"expense","normal":"debit"},
    {"code":"6206","name":"INSAFORP","type":"expense","normal":"debit"},
    {"code":"6207","name":"Alquiler de Local","type":"expense","normal":"debit"},
    {"code":"6208","name":"Servicios Basicos (Agua, Luz, Telefono)","type":"expense","normal":"debit"},
    {"code":"6209","name":"Papeleria y Utiles de Oficina","type":"expense","normal":"debit"},
    {"code":"6210","name":"Honorarios Profesionales","type":"expense","normal":"debit"},
    {"code":"6211","name":"Gastos Legales y Notariales","type":"expense","normal":"debit"},
    {"code":"6212","name":"Seguros","type":"expense","normal":"debit"},
    {"code":"6213","name":"Mantenimiento y Reparaciones","type":"expense","normal":"debit"},
    {"code":"6214","name":"Depreciacion — Equipo Administrativo","type":"expense","normal":"debit"},
    {"code":"6215","name":"Amortizacion de Intangibles","type":"expense","normal":"debit"},
    {"code":"6216","name":"Combustibles y Lubricantes","type":"expense","normal":"debit"},
    {"code":"6217","name":"Cuotas y Suscripciones","type":"expense","normal":"debit"},
    {"code":"6218","name":"Programas y Licencias Informaticas","type":"expense","normal":"debit"},
    {"code":"6219","name":"Gastos de Capacitacion","type":"expense","normal":"debit"},
    {"code":"6220","name":"Estimacion para Cuentas Incobrables","type":"expense","normal":"debit"},
    {"code":"6221","name":"Impuestos Municipales","type":"expense","normal":"debit"},
    {"code":"6222","name":"Otros Gastos de Administracion","type":"expense","normal":"debit"},
    # GRUPO 7 — FINANCIEROS / NO OPERACIONALES
    {"code":"7101","name":"Intereses sobre Prestamos","type":"expense","normal":"debit"},
    {"code":"7102","name":"Comisiones Bancarias","type":"expense","normal":"debit"},
    {"code":"7103","name":"Intereses Moratorios","type":"expense","normal":"debit"},
    {"code":"7104","name":"Perdida por Diferencial Cambiario","type":"expense","normal":"debit"},
    {"code":"7105","name":"Gastos No Deducibles","type":"expense","normal":"debit"},
    {"code":"7106","name":"Perdida en Venta de Activo Fijo","type":"expense","normal":"debit"},
    {"code":"7107","name":"Gastos Extraordinarios","type":"expense","normal":"debit"},
    {"code":"7201","name":"Productos Financieros (Intereses Ganados)","type":"income","normal":"credit"},
    {"code":"7202","name":"Ganancia por Diferencial Cambiario","type":"income","normal":"credit"},
    {"code":"7203","name":"Utilidad en Venta de Activo Fijo","type":"income","normal":"credit"},
    {"code":"7204","name":"Otros Ingresos No Operacionales","type":"income","normal":"credit"},
    {"code":"7301","name":"ISR del Ejercicio","type":"expense","normal":"debit"},
]

NIIF_SV_ENTRY_MAP = {
    ("ingreso", "Ventas"):        ("1201", "4101"),
    ("ingreso", "Servicios"):     ("1201", "4103"),
    ("gasto",   "Compras"):       ("5101", "2101"),
    ("gasto",   "Personal"):      ("6201", "2301"),
    ("gasto",   "Servicios"):     ("6210", "2104"),
    ("gasto",   "Renta"):         ("6207", "2104"),
    ("gasto",   "Marketing"):     ("6103", "2104"),
    ("gasto",   "Viajes"):        ("6107", "1103"),
    ("gasto",   "Software"):      ("6218", "2104"),
    ("gasto",   "Mantenimiento"): ("6213", "2104"),
    ("gasto",   "Seguros"):       ("6212", "2104"),
    ("gasto",   "ISR"):           ("7301", "2205"),
    ("gasto",   "Intereses"):     ("7101", "1103"),
    ("ingreso", "Intereses"):     ("1103", "7201"),
    ("ingreso", "Activos"):       ("1103", "7203"),
}

NIIF_SV_DEFAULT_GASTO   = ("6222", "2101")
NIIF_SV_DEFAULT_INGRESO = ("1201", "4101")


def get_entry_accounts_sv(tipo: str, categoria: str):
    """Devuelve (cuenta_debe, cuenta_haber) para un registro dado."""
    key = (tipo, categoria)
    if key in NIIF_SV_ENTRY_MAP:
        return NIIF_SV_ENTRY_MAP[key]
    return NIIF_SV_DEFAULT_GASTO if tipo == "gasto" else NIIF_SV_DEFAULT_INGRESO
